name: RedDevPlugin
main: me.zacklukem.RedDevPlugin
version: 1.0
commands:
     reddevtest:
          description: Use To Test If RedDevPlugin is enabled or not.
          usage: /<command>
     server-name:
          description: Name the server
          usage: /<command>