name: RedDevPlugin
main: me.zacklukem.RedDevPlugin
version: 0.6
commands:
     reddevtest:
          description: Use To Test If RedDevPlugin is enabled or not.
          usage: /<command>
     server-name:
          description: Name the server
          usage: /<command>
     trade:
          description: Trade diamonds for emeralds
          usage: /<command>